### ISSUE TITLE
Enhancement: Add possibility to access setOnCancelListener and setNegativeButton

### ISSUE THREAD

**Issue by SeppPenner** [hedzr/android-file-chooser#10]
Hi, it would be a great improvement to have the opportunity to acces the **setOnCancelListener** and **setNegativeButton** methods from the **AlertDialog.Builder** class.

**Comment by SeppPenner** [comment]
I've created a gist for that one: https://gist.github.com/SeppPenner/c72e3e3cd90702c42355a12b7bcad2c9

The main changes would be to add two methods:

```java
public void setNegativeButton(@StringRes int textId, final DialogInterface.OnClickListener listener){
        builder.setNegativeButton(textId, listener);
    }

    public void setOnCancelListener(DialogInterface.OnCancelListener listener){
        builder.setOnCancelListener(listener);
}
```

put the builder variable globally:

```java
    //...
    private @DrawableRes
    int _iconRes = -1;
    private @LayoutRes
    int _layoutRes = -1;
    private String _dateFormat;
    private AlertDialog.Builder builder;
```

, update the build() method (removed the whole stuff with setting negative button here)
and adjust the check on top of the build() method like following:

```java
 public ChooserDialog build() {
        if (_titleRes == 0 || _okRes == 0) {
            throw new RuntimeException("withResources() should be called at first.");
        }
//...
}
```

However, I do not know if this can be done in another way as it destroys the method chaining style the library is written in, but my suggestion would need to remove the with(Context) method and add this directly to the constructor:

```java
public ChooserDialog(Context context) {
        this._context = context;
        builder = new AlertDialog.Builder(_context);
    }
```

An empty constructor would then not exist any longer...

That's also why I didn't create a pull request for this topic.

**Comment by hedzr** [comment]
Thx for your suggestion.  
 
I have another consideration is whether there is a way to make the new improvements and the old style method calling coexist.
 
Would you mind to separate your thoughts into 2 parts?  The first one is some new functions if your think it’s useful or more convenient for every user. So I can simply merge it into new version. The other one I think there’s some changes have to make to maintain the backwards compatibility.

**Comment by SeppPenner** [comment]
Hi @hedzr, I will try to provide 1 (or more) pull requests in the future when I have time. I will check to provide backwards compatibility, too. (I know, my update was just a quick and dirty fix)

**Comment by hedzr** [comment]
😙, i'd maken a new release, because my hands are out of control. Hope it's useful.

**Comment by SeppPenner** [comment]
Hi @hedzr. Did you already add my suggestions to your code? It seems so if I look to the ChooserDialog.java class:

```java
 public ChooserDialog withNegativeButton(@StringRes int cancelTitle,
            final DialogInterface.OnClickListener listener) {
        this._negativeRes = cancelTitle;
        this._negativeListener = listener;
        return this;
    }

    public ChooserDialog withNegativeButtonListener(final DialogInterface.OnClickListener listener) {
        this._negativeListener = listener;
        return this;
    }

    /**
     * it's NOT recommended to use the `withOnCancelListener`, replace with `withNegativeButtonListener` pls.
     */
    public ChooserDialog withOnCancelListener(final DialogInterface.OnCancelListener listener) {
        this._cancelListener2 = listener;
        return this;
    }
```

In my opinion, this is already the solution I wanted to have :D

**Comment by hedzr** [comment]
yes, here is it
