### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by abbasalim** [hedzr/android-file-chooser#12]
`Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.obsez.android.lib.filechooser:filechooser:1.1.6.
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.obsez.android.lib.filechooser:filechooser:1.1.6.
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.obsez.android.lib.filechooser:filechooser:1.1.6.
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.obsez.android.lib.filechooser:filechooser:1.1.6.
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.obsez.android.lib.filechooser:filechooser:1.1.6.
Open File
Show Details
`

**Comment by hedzr** [comment]
i'm sorry it's too fast about AS upgrades. `master` will be updated for AS 3.1.2 in a few days. asap.

**Comment by hedzr** [comment]
jitpack usage:
implementation 'com.github.hedzr:android-file-chooser:v1.1.10'
