### ISSUE TITLE
Customize colors

### ISSUE THREAD

**Issue by lucian-cm** [hedzr/android-file-chooser#13]
The library is great. Do you plan to add item color and date color to allow customization or add theme support?

**Comment by hedzr** [comment]
suppose a new `withRowView(resId)` to allow replace `li_row_textview` with another one, so you could customize the text color or even more, how about that?

**Comment by lucian-cm** [comment]
Sounds good 👍

**Comment by lucian-cm** [comment]
@hedzr thanks :+1:
