### ISSUE TITLE
Customize icons for folder and file

### ISSUE THREAD

**Issue by lucian-cm** [hedzr/android-file-chooser#14]
Do you plan to also add the possibility to change the icons for folder and file?

**Comment by hedzr** [comment]
well, it's possible.

**Comment by hedzr** [comment]
it maybe what you want: `withFileIcons(resolveMime, fileIcon, folderIcon)`, `withFileIconsRes(resolveMime, fileIconResId, folderIconResId)`, and `withAdapterSetter(setter)`.

**Comment by lucian-cm** [comment]
Thanks for the prompt reply. I will test 1.1.9 tonight and let you know 👍

**Comment by lucian-cm** [comment]
Works great, very nice addition, closing issue.
