### ISSUE TITLE
Secure up navigation

### ISSUE THREAD

**Issue by lucian-cm** [hedzr/android-file-chooser#15]
It would be a nice thing to have an option to secure the up level navigation. For example, one can have the following use case: start in a certain path but don't want to allow navigation further than
`getExternalStorageDirectory()`, basically meaning that the user cannot change from primary storage to SD card for a certain file/folder picker task. Or for example an application that allows to save resources only in an app specific folder structure, so navigating outside that app root folder is not allowed and other such scenarios.
Also it would be nice to have a callback for when the up navigation is disabled because you reached the set folder e.g. `withNavigateUpTo(folder, callback)`.

**Comment by hedzr** [comment]
good idea!

**Comment by hedzr** [comment]
although they are rare, but it's right thing to give a callback on navigating up; and perhaps another hook at any navigations is useful too.

**Comment by lucian-cm** [comment]
Closing because fix is included in 1.1.10
