### ISSUE TITLE
Cannot go up to /emulated/0

### ISSUE THREAD

**Issue by lucian-cm** [hedzr/android-file-chooser#16]
I've noticed that going up function has changed when the following code was added in `ChooserDialog`.java. This causes the side effect that you cannot navigate up from that point onwards. Maybe the test should be `(_currentDir.getParentFile() != null) && f.canRead() && (f.listFiles().length == 0)`. This happens on Android 6.
I think the code should be to allow up navigation until it is possible irrespective if you can show the items in that folder. 
```
if (f.canRead()) {
_currentDir = f;
 } else {
 Toast.makeText(this._context, "Couldn't go up level", Toast.LENGTH_SHORT).show();
}
```

**Comment by hedzr** [comment]
i'll test that case later, thanks your points

**Comment by hedzr** [comment]
`f != null` should be added, you're right. `f.listFiles().length` could be ignored, in my sight.
