### ISSUE TITLE
Crash on Fragment 

### ISSUE THREAD

**Issue by sajid-verveba** [hedzr/android-file-chooser#17]
Crash Error : -
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File[] java.io.File.listFiles(java.io.FileFilter)' on a null object reference
                                                                        at com.obsez.android.lib.filechooser.ChooserDialog.listDirs(ChooserDialog.java:288)
                                                                        at com.obsez.android.lib.filechooser.ChooserDialog.refreshDirs(ChooserDialog.java:371)
                                                                        at com.obsez.android.lib.filechooser.ChooserDialog.build(ChooserDialog.java:204)
                                                                        at com.verveba.pimapp.view.frgmnts.LocTestingWorstPortFragment.chooseDTPFile(LocTestingWorstPortFragment.java:304)
```

Following code used in fragment : - 

```
new ChooserDialog().with(getActivity())
                .withFilter(false, false, "jpg", "jpeg", "png")
                .withResources(R.string.dtp_file, R.string.title_choose, R.string.dialog_cancel)
                .withChosenListener(new ChooserDialog.Result() {
                    @Override
                    public void onChoosePath(String path, File pathFile) {
                      
                        }
                    }
                })
                .build()
                .show();
```

**Comment by hedzr** [comment]
add `.withStartFile(startingDir)`

**Comment by angujo** [comment]
Experiencing the same here. Log is;

> java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File[] java.io.File.listFiles(java.io.FileFilter)' on a null object reference
>         at com.obsez.android.lib.filechooser.ChooserDialog.listDirs(ChooserDialog.java:288)
>         at com.obsez.android.lib.filechooser.ChooserDialog.refreshDirs(ChooserDialog.java:371)
>         at com.obsez.android.lib.filechooser.ChooserDialog.build(ChooserDialog.java:204)

My code is:

```
 btnUpload.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                new ChooserDialog().with(getActivity())
                        .withStartFile("")
                       // .withStartFile(Environment.getExternalStorageState()+"/")
                        .withFilterRegex(false, false, ".*\\.(jpe?g|png)")
                        .withChosenListener(new ChooserDialog.Result() {
                            @Override
                            public void onChoosePath(String path, File pathFile) {
                                Toast.makeText(getContext(), "FILE: " + path, Toast.LENGTH_SHORT).show();
                            }
                        })
                        .build()
                        .show();
.............................
```

Kindly assist.
**EDIT:**
It failed even with  `.withStartFile(Environment.getExternalStorageState()+"/")`

**Comment by hedzr** [comment]
it seems that caused by `_currentDir` is null, in [ChooserDialog.java#L312](ChooserDialog.java#L312): `File[] files = _currentDir.listFiles(_fileFilter);`, with an earlier version used. so:
- try the newest version `1.1.9`
- withStartFile(null), or .withStartFile(Environment.getExternalStorageDirectory().getAbsolutePath()),
- ~~make sure permissions XX_WRITE_EXTERNAL_STORAGE~~
- ~~post a sample repo link that can reproduce the errors and let me have a try.~~
- or debug deep into the source codes.

**Comment by hedzr** [comment]
just checked: `withStartFile("")` cause `_currentDir == null`.
as a workaround, replace it with `withStartFile(null)` or `.withStartFile(Environment.getExternalStorageDirectory().getAbsolutePath())`.
