### ISSUE TITLE
ExtFileFilter crashes if a folder contain a file without extension

### ISSUE THREAD

**Issue by mkeresztes** [hedzr/android-file-chooser#2]
Hi,

I launch the file chooser using your sample code:
`new ChooserDialog().with(getActivity())
    .withFilter(false, false, "db", "zip", "zi_")
    .withStartFile(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getAbsolutePath())
    .withChosenListener(
        new ChooserDialog.Result() {
                                    @Override
                                    public void onChoosePath(String path, File pathFile) {
                                        Toast.makeText(getActivity(), "FILE: " + path, Toast.LENGTH_SHORT).show();
                                    }
                                })
    .build()
    .show();
`

If I navigate to a folder that contains a file without an extension, the chooser crash. Please find the callstack attached.

Thank you

[callStack.txt](https://github.com/hedzr/android-file-chooser/files/1103326/callStack.txt)

**Comment by hedzr** [comment]
checking

**Comment by hedzr** [comment]
really ugly mistake. confirmed. update after a while. thank you @mkeresztes

**Comment by hedzr** [comment]
new release: 1.1.5 was available.

**Comment by mkeresztes** [comment]
Thanks @hedzr 
Your file chooser is one of the bests available on market!
