### ISSUE TITLE
Can I Contribute logo for Android File Chooser ?

### ISSUE THREAD

**Issue by iqbalhood** [hedzr/android-file-chooser#20]
Hello @hedzr. Can I Contribute to make Logo For This Project ?

**Comment by hedzr** [comment]
Sounds great! the new icon will be used in library homepage and as the demo app main icon.

**Comment by iqbalhood** [comment]
Hello Sir @hedzr ,
These are my logo proposal for your application. If there any revision, please just tell it.
![fchooser](https://user-images.githubusercontent.com/1563756/41197998-d1004078-6c97-11e8-92ff-7750e74c4dd5.jpeg)

**Comment by hedzr** [comment]
it's fine. could you pls make a png copy within readme.md.

**Comment by iqbalhood** [comment]
Off course,  please give me your email . I Will send you the editable format and readme.md file.

**Comment by hedzr** [comment]
thank you @iqbalhood, i'll check hedzrz@gmail.com

**Comment by iqbalhood** [comment]
Hello sir, Thanks For Choosing My Logo. I Hope u can use my logo in this project. I Have Sent Email With Editable File To You :)

**Comment by hedzr** [comment]
done and close
