### ISSUE TITLE
Permission dialog have open every time.

### ISSUE THREAD

**Issue by UmeshBaldaniya46** [hedzr/android-file-chooser#21]
Hello 
Good Work..

I have one issues while show ChooserDialog, issues is  permission dialog have open every time, if i have allow to access those permissions

I have fount where is wrong

You code 
`  int PERMISSION_REQUEST_READ_EXTERNAL_STORAGE = false;
                ActivityCompat.requestPermissions((Activity)this._context, new String[]{"android.permission.READ_EXTERNAL_STORAGE"}, 0);
                int permissionCheck = ContextCompat.checkSelfPermission(this._context, "android.permission.READ_EXTERNAL_STORAGE");
                if (permissionCheck == 0) {
                    this._alertDialog.show();
                }`
why you are ask requestPermissions before permissionCheck
Please change you code aspa

`        val permissionCheck = ContextCompat.checkSelfPermission(this, "android.permission.READ_EXTERNAL_STORAGE")
        Log.e("TAG", " permissionCheck " + permissionCheck)
        if (permissionCheck == 0) {
            this._alertDialog.show()
        }else{
            ActivityCompat.requestPermissions(this as Activity, arrayOf("android.permission.READ_EXTERNAL_STORAGE"), 0)
        }`

Thanks..
![device-2018-08-11-162815](https://user-images.githubusercontent.com/27193416/43991160-3b34e0ee-9d84-11e8-9934-7cda140587ee.png)

**Comment by hedzr** [comment]
i do some checks first asap.

**Comment by hedzr** [comment]
It's very much appreciated.
