### ISSUE TITLE
Can the title of the dialog be removed?

### ISSUE THREAD

**Issue by Vierco** [hedzr/android-file-chooser#23]
Otherwise, you can change the color of the title and the "cancel" button?
Thanks for your work.

**Comment by hedzr** [comment]
two ways:
1. give an empty title string resource like: `<string name="title_nothing"></string>`, and set as main title:
   ```java
   .withResources(R.string.title_nothing, R.string.title_ok, R.string.dialog_cancel)
   ```
2. try the temporary `disableTitle(true)` on the newest `master` branch.

good luck.
