### ISSUE TITLE
Error:(16, 0) path may not be null or empty string. path='null' <a href="openFile:H:\Project\studio2.3_workspace\android-file-chooser-master\app\build.gradle">

### ISSUE THREAD

**Issue by RoyNeverGiveUp** [hedzr/android-file-chooser#3]
signingConfigs {
        Properties properties = new Properties()
        properties.load(project.rootProject.file('local.properties').newDataInputStream())
        def sdkDir = properties.getProperty('sdk.dir')
        def ndkDir = properties.getProperty('ndk.dir')
        def ksPath = properties.getProperty('KS_PATH')
        def keystorePropertiesFile = rootProject.file(ksPath) //"../keystore.properties")  //something here
        def keystoreProperties = new Properties()
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
        config {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

**Comment by hedzr** [comment]
add `KS_PATH` to your local.properties, and point to the exact path, if u wanna rebuild or try this repo:

```bash
KS_PATH=/Users/android-test/android/published/keystore.properties
```

and, `keystore.properties` looks like:

```bash
keyAlias=android-test
keyPassword=password
storeFile=/Users/android-test/android/android-file-chooser.keystore
storePassword=password
```

**Comment by bostrot** [comment]
You can also just remove this part if you don't need to sign it.
