### ISSUE TITLE
Remote control not working

### ISSUE THREAD

**Issue by YouROK** [hedzr/android-file-chooser#30]
Please add d-pad support, actual on tvbox

**Comment by hedzr** [comment]
it should work properly. but i only tested in emulator.

**Comment by Guiorgy** [comment]
Pfff. Well you got it first... I was about to send a pull request.

**Comment by hedzr** [comment]
:)

**Comment by Guiorgy** [comment]
@hedzr , I really like what you did with the left and right buttons, but there are issues:
1. when going down it seem to always scroll from top again and again?
2. neutral/positive/negative buttons are unreachable
3. it breaks selectMultiple mode :( (also the selected view in Dpad mode and select multiple looks exactly the same, which may be confusing)

**Comment by Guiorgy** [comment]
@hedzr , I just looked at your code, and I am pretty sure you don't need to track which item is selected in the list manually, it only causes problems. Android can do it itself! you just need to:

```
_list.setSelector(R.drawable.listview_item_selector);
 _list.setDrawSelectorOnTop(true);
 _list.setItemsCanFocus(true);
```

and it will do it for you...

PS. here's my version, if you are interested:
![dpad](https://user-images.githubusercontent.com/27736965/46207662-35ebd400-c339-11e8-95c4-3345e9c7d49c.gif)

**Comment by hedzr** [comment]
good advice for me. i'll rewrite this night.
ps: i'll hold the assignee on an issue next time, for this one too.

**Comment by Guiorgy** [comment]
@hedzr , i mean, I can send you a pull request?

**Comment by YouROK** [comment]
I did not see the code, but
For selections items in xml layout I use:

item layout
android:focusable="true"
android:clickable="true"
android:foreground="?android:selectableItemBackground"

sorry for bad english

**Comment by hedzr** [comment]
@Guiorgy , yes u can do that right now, my pleasure.

**Comment by hedzr** [comment]
@YouROK following the https://jitpack.io usage (and README.md) if u wanna try the newest code on the `master` branch.

currently,
it is the temporary codes in my master branch.
> this strategy will be improved in the future.

stable version has `release/vx.x.x`/`vx.x.x`/`x.x.x` tag.

**Comment by Guiorgy** [comment]
@hedzr , there ya go ;)
if there's anything else you need help with, let me know. I might be able to help.

**Comment by YouROK** [comment]
D-pad works, thanks

**Comment by Guiorgy** [comment]
@YouROK , glad to hear that :). Though still, it has only been tried on an emulator, so do test it and come back if you find any issues.

**Comment by YouROK** [comment]
I tested on device, works fine

**Comment by hedzr** [comment]
so, it's okay, **for the present,** the top commit be kept and #31 be hold.

@Guiorgy , thank you for your time, and the points you mentioned i'll review later, the new pr too.
