### ISSUE TITLE
Writing to external storage

### ISSUE THREAD

**Issue by lintax** [hedzr/android-file-chooser#33]
For some reason in the last version 1.1.11 you have added a request to write to external storage, giving no option for app owner to disable this. Since some apps definitely do not plan writing there, it is excess permission to request.
Probably the best way would be to configure whatever the processing mode should be with write or not.

**Comment by hedzr** [comment]
yes, you’re right.

**Comment by hedzr** [comment]
@lintax here is a patch on 1.1.11 and master branch.

In `afc`, as i known, we only need WRITE permission when we creating a new folder or delete it (`enableOptions(true)`). So, this patch should works probably.
No more modifications at the user (client or developer) side needed.

**Comment by lintax** [comment]
Yes, thanks for quick resolution

**Comment by Guiorgy** [comment]
is it just me, or when only requesting READ permission, WRITE is also granted...

**Comment by hedzr** [comment]
really? u don't say the new commit not work, do u?

**Comment by hedzr** [comment]
i need test on the scene you said, if i get your point exactly.
when requesting WRITE, the READ will be requested implicitly. but i'm not sure about the opposite side

**Comment by Guiorgy** [comment]
So, I think what happens is, if I give Read permission and then try opening a dialog with options enabled, Write permission is still -1, but no permission request appears on screen, next thing I know, Write permission was granted...
