### ISSUE TITLE
How to theme this. Ex a Dark theme ?

### ISSUE THREAD

**Issue by ytheekshana** [hedzr/android-file-chooser#34]
Hello. Any way to theme this.......Like dark theme and light theme

**Comment by hedzr** [comment]
Well, it's a really good question. `afc` has no yet been in better conformance with System Theme.  But that's not very hard to be done. *Three* things here:
1. suppose that you're in AppCompat Day/Night schema
2. using your row layout with `.withRowLayoutView(li_row_textview)`. you can copy the default one from library layout resource folder (`li_row_textview.xml`), and update its background:
   ```xml
   <RelativeLayout android:background="?android:attr/selectableItemBackground" ...
   ```
3. All forks.

I will make this change in `1.2.x` & `devel` branch later, but you have to setup a custom row layout resource before the next generation released.

**Comment by ytheekshana** [comment]
Perfect
