### ISSUE TITLE
Cannot navigate up on 1.1.11

### ISSUE THREAD

**Issue by gswierczynski** [hedzr/android-file-chooser#35]
Just started looking into this library and if I am not mistaken there is some regression on 1.1.11 and it is impossible to navigate up.
Using this simple snippet.
Pixel 3, 9.0
```
ChooserDialog(context)
    .withStartFile(Environment.getExternalStorageDirectory().absolutePath)
    .withNavigateTo { true }
    .withNavigateUpTo { true }
    .build()
    .show()
```

**Comment by hedzr** [comment]
Can the parent of `Environment.getExternalStorageDirectory().absolutePath` be read or not? could you print `its.canRead()`.
`withNavigateTo` & `withNavigateUpTo` follow the folder read and write permissions.

**Comment by gswierczynski** [comment]
I will check it tomorrow, but I assumed that it is regression since navigating up works fine when I change version to 1.1.10

**Comment by hedzr** [comment]
such being the case, expecting for more details. thanks.

**Comment by gswierczynski** [comment]
Hi,

Sorry for the delay.

When using 1.1.11:
File(Environment.getExternalStorageDirectory().absolutePath) - canRead = true
File(Environment.getExternalStorageDirectory().absolutePath).parentFile - canRead = false

It is possible to navigate to one of the folders, but it is impossible to navigate up from it.

When using: 1.1.10:
File(Environment.getExternalStorageDirectory().absolutePath) - canRead = true
File(Environment.getExternalStorageDirectory().absolutePath).parentFile - canRead = false

It is possible to navigate up even from base directory.

Like I said, downgrading to 1.1.10 solves the issue.

**Comment by hedzr** [comment]
@gswierczynski , do you mean you're going up from `/sdcard`? Anyway, i'd restricted the `canRead()` check. It prevents the further action at NON-canRead parent directory. So you can't navigate up to a folder if its.`canRead()` return `false`. And this is a feature, but v1.1.10 or below may lost it.

For: `File(Environment.getExternalStorageDirectory().absolutePath).parentFile - canRead = false`.
checker inside `listDir()`: [ChooserDialog.java#L978](https://github.com/hedzr/android-file-chooser/blob/c975112c06f9e47d9903d70fae0f2a20043e6f1b/library/src/main/java/com/obsez/android/lib/filechooser/ChooserDialog.java#L978)

**Comment by hedzr** [comment]
it seems a bug there, i'll debug it tonight.

**Comment by hedzr** [comment]
on v1.x, _list's focus cause the `goBack()` skip the real action. try the new patch on `master`:
```gradle
implementation 'com.github.hedzr:android-file-chooser:bc584ab9e5'
```
it's a temporary patch. i hope it works without unexpected effects.

**Comment by hedzr** [comment]
on 1.2.x, the fully fixes applied...

**Comment by Kadanza** [comment]
'com.github.hedzr:android-file-chooser:master-SNAPSHOT' dont work for me now. 
I have unresolved reverence ChooserDialog.

Clear and rebuild dont help me. 
com.github.hedzr:android-file-chooser:v1.1.11  I  can import class, but there are no dialog. 

In past com.github.hedzr:android-file-chooser:master-SNAPSHOT worked for me

**Comment by hedzr** [comment]
### for jitpack.io, these settings would be recommended:

```gradle
buildscript {
  configurations.all {
      resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
      resolutionStrategy.cacheDynamicVersionsFor 0, 'seconds'
  }
}
```

They will [disable gradle cache](https://docs.gradle.org/current/userguide/introduction_dependency_management.html#changing-module-cache-control) for jitpack. Put them into your top level `build.gradle`, and `File\Synchronize project with gradle files`, and i hope it'll work as is.

In my local demo project, it works:
```gradle
// might not work now and i have no idea:
// implementation 'com.github.hedzr:android-file-chooser:master-SNAPSHOT'
// Or, hashed-code works with my local demo:
implementation 'com.github.hedzr:android-file-chooser:d6aa2c4f1b'
```
please retry `sync ...` if downloading .pom and .jar failed.
good luck.

### if you're still not lucky

one minute ago i just pushed **v1.1.14** to jcenter with my newest `master` branch. it includes the patches since 1.1.11.
so, trying from jcenter:

```gradle
implementation 'com.obsez.android.lib.filechooser:filechooser:1.1.14'
```
> ~~PS: wait a minute, it seems bad. i'm checking on jcenter.~~
> **1.1.14 or later** ready.

good luck too.

**Comment by hedzr** [comment]
should be closed.
