### ISSUE TITLE
Project won't build.

### ISSUE THREAD

**Issue by HappyAmos** [hedzr/android-file-chooser#37]
Not sure what's going on, but my project won't build anymore, because it says it resolve:

import com.obsez.android.lib.filechooser.ChooserDialog;

My project was working great two days ago. I currently have your build specified as:
    implementation 'com.github.hedzr:android-file-chooser:master-SNAPSHOT'

...so, I am subject to unexpected issues on each push, which is my fault. But, I also reverted to
   implementation 'com.obsez.android.lib.filechooser:filechooser:1.1.0'

and I still get build errors. I'm not sure what I did wrong, or if something got goofed?

**Comment by HappyAmos** [comment]
Ok, slight change. I tried building with 1.1.11 and it built just fine. 1.2.0 won't build properly
`Failed to resolve: com.obsez.android.lib.filechooser:filechooser:1.2.0
Show in File
Show in Project Structure dialog
`

**Comment by hedzr** [comment]
i have no done at `1.2.0`. there is a in-progress working branch `x1.2.0` if you like it.

**Comment by HappyAmos** [comment]
That would explain it! Either way the master-SNAPSHOT channel isn't working, so I will just stick with 1.1.11 which is still working fine.

**Comment by hedzr** [comment]
Sometimes jitpack can't work on a modified branch with its name such as `master-SNAPSHOT`. You might try:
```gradle
implementation 'com.github.hedzr:android-file-chooser:bc584ab9e5'
```
That's a newest commit hash-code of master and 1.1.11 patch. To check the git hashcode, open: https://jitpack.io/#hedzr/android-file-chooser, and switch to `Commits` pane.

**Comment by HappyAmos** [comment]
Even using a commit, it still doesn't work: 
`implementation 'com.github.hedzr:android-file-chooser:bc584ab9e5'`

To test:
1. I create that line above in my Module:build.gradle
2. File ==> Invalidate Caches / Restart...
3. File => Sync with File System
4. Sync Project with Gradle Files
5. Build

Project fails: 
`error: package com.obsez.android.lib.filechooser does not exist`

Now, if I change to:
`implementation 'com.obsez.android.lib.filechooser:filechooser:1.1.11'` it will build perfectly, but I'm stuck with an older version.

**Comment by hedzr** [comment]
I have no idea to jitpack.io.

There are some advices in my reply in #35 .
And you may trying to use v1.1.14 via jcenter currently.
:(

### NOTE HERE

It's strongly recommended to retrieve v1.1.14 via jcenter.

```gradle
implementation 'com.obsez.android.lib.filechooser:filechooser:1.1.14'
```

or jitpack:

```gradle
// implementation 'com.github.hedzr:android-file-chooser:master-SNAPSHOT'
// or
implementation 'com.github.hedzr:android-file-chooser:d6aa2c4f1b'
```

**Comment by hedzr** [comment]
should be closed.

**Comment by HappyAmos** [comment]
Yes. Not sure what was going on with JitPack. I have tried a recent build and everything worked great.

Thanks!
