### ISSUE TITLE
On android P when obtaining rights to read and write.

### ISSUE THREAD

**Issue by Zevsus** [hedzr/android-file-chooser#39]
It shows nothing, but if you restart the application, it displays the folders.

**Comment by hedzr** [comment]
That's it. `ActivityCompat.requestPermissions()` is asynchronously, so i can't block there and show dialog again after it.
To avoid it, using RxPermissions or others and obtain the rights yourself.

Or tip me if you are any good idea.

> but, it might not be planned to package a hidden activity.

**Comment by Zevsus** [comment]
thnx
