### ISSUE TITLE
Changing design

### ISSUE THREAD

**Issue by MoMannn** [hedzr/android-file-chooser#4]
Is there anyway to override resources and styles to change text colors/paddings/background color etc?

**Comment by bostrot** [comment]
Yes, just edit the style in the library and rebuild it. Also take a look at li_row_textview.xml.

**Comment by riskiadi** [comment]
Flat Custom Interface

![image](https://user-images.githubusercontent.com/18738645/38465873-32809894-3b4b-11e8-9b3f-0e2f49edd957.png)

**Comment by riskiadi** [comment]
Flat Custom Interface

![image](https://user-images.githubusercontent.com/18738645/38465934-d55eb474-3b4b-11e8-8671-a161ae352904.png)
