### ISSUE TITLE
How to open external storage?

### ISSUE THREAD

**Issue by MJsaycon** [hedzr/android-file-chooser#40]
The defaullt directory is my internal directory how can I open the external directory(SDCARD).

**Comment by hedzr** [comment]
1. The first entry in file/folder list should be [..SDCard] or [..Primary Storage], which can switch your `root`
2. set startPath with `withStartFile(your-external-path)`

**Comment by MJsaycon** [comment]
Is there something wrong with my directory? I can't see any files in my external directory after tapping the SDCard Storage. What am I using right now is the android pie version.

**Comment by hedzr** [comment]
no special rights should be decl explicitly, `afc` did.
Inside `afc`, the sdcard path will be retrieved by `FileUtil.getStoragePath(cxt, true)`, would you please check its result and share them here.

**Comment by MJsaycon** [comment]
this is the return directory "/mnt/media_rw/6436-3031", do I need to add some codes?

**Comment by hedzr** [comment]
i guess that is a right path to point to the right /sdcard, so, it looks good.
Well, does it being used with the newest version of `afc`, i mean, 1.14.
And if it is, i'm afraid that i need more details, such as: true device or emulator, did your app prompt the permission dialog and approved, and the codes invoking `afc`, ...

**Comment by hedzr** [comment]
the permissions are: `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE`. i don't think this is a matter.

**Comment by MJsaycon** [comment]
String string = FileUtil.getStoragePath(getActivity(),true);  // result /mnt/media_rw/6436-3031

after setting the path in withStartFile("/mnt/media_rw/6436-3031")
list of Directories that shows:
-appfuse
-asec
-expand
-media_rw
-obb
-runtime
-sdcard
-secure
-update_engine
-user

after tapping the sdcard it returns my internal storage directory

**Comment by hedzr** [comment]
ok, it seems my fault, i'll debug it and post the patch asap. thank you @MJsaycon

**Comment by MJsaycon** [comment]
yes I did I used a runtime permission before the user can used the storage. I also check it in my permission from app settings and the storage permission is indeed enable.

These are the permissions that I used.
  String[] permissions = {Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE};

**Comment by hedzr** [comment]
i can't reproduce your scene, with an emulator. did i miss anything?

**Comment by MJsaycon** [comment]
FileUtil.getStoragePath(getActivity(),true); this code means to get the removable storage right? I'm confused because it's returning my internal directory not my removable SDCARD. I don't know but it seems that it is treating my internal storage as my sdcard? I don't know about using emulator I did not test  it yet.

**Comment by hedzr** [comment]
Yep, it uses [StorageManager](https://developer.android.com/reference/android/os/storage/StorageManager) and works fine with emulator and real mobile, in my tests.
...

**Comment by hedzr** [comment]
`getStoragePath()` list all mount points and check its `isRemovable` property, and return internal storage path if no removable mount points found. so, would u like uncomment the debug lines to find out what happen, if time permits.

**Comment by MJsaycon** [comment]
`String SD_CARD = "sdCard";
    String EXTERNAL_SD_CARD = "externalSdCard";
    String ENV_SECONDARY_STORAGE = "SECONDARY_STORAGE";

    public Map<String, File> getAllStorageLocations() {
        Map<String, File> storageLocations = new HashMap<>(10);
        File sdCard = Environment.getExternalStorageDirectory();
        storageLocations.put(SD_CARD, sdCard);
        final String rawSecondaryStorage = System.getenv(ENV_SECONDARY_STORAGE);
        if (!TextUtils.isEmpty(rawSecondaryStorage)) {
            String[] externalCards = rawSecondaryStorage.split(":");
            for (int i = 0; i < externalCards.length; i++) {
                String path = externalCards[i];
                storageLocations.put(EXTERNAL_SD_CARD + String.format(i == 0 ? "" : "_%d", i), new File(path));
            }
        }
        return storageLocations;
    }`

I also try this code from this [link](https://stackoverflow.com/questions/39850004/android-get-all-external-storage-path-for-all-devices) but still it is returning my internal?

**Comment by hedzr** [comment]
is it a special device? or a custom android os? or a special /sdcard link or mount point?
in according with official document, sdcard must have a `true` `isRemovable`.
my suggestion is using `withStartFile()` temporarily, how about you?

**Comment by MJsaycon** [comment]
I'm using a Huawei Honor Play(Pie) device and they have a special OS,  I test it with another device and it reads the external of Samsung J7 pro(Oreo). How can I resolve it specially with those custom devices?

**Comment by hedzr** [comment]
do u have any cases to find out the exactly external storage path programmatically? if yes, i may try my best to merge the detecting codes.
or, how about to use the explicit root path?

**Comment by hedzr** [comment]
and you can try this version:

```java
    @NonNull
    public static String getStoragePath(Context context, boolean isRemovable) {
        StorageManager storageManager = (StorageManager) context.getSystemService(Context.STORAGE_SERVICE);
        Class<?> storageVolumeClazz = null;
        try {
            storageVolumeClazz = Class.forName("android.os.storage.StorageVolume");
            Method getVolumeList = storageManager.getClass().getMethod("getVolumeList");
            Method getPath = storageVolumeClazz.getMethod("getPath");
            Method isRemovableMtd = storageVolumeClazz.getMethod("isRemovable");
            Object result = getVolumeList.invoke(storageManager);
            final int length = Array.getLength(result);
            Timber.d("---length--" + length);
            for (int i = 0; i < length; i++) {
                Object storageVolumeElement = Array.get(result, i);
                Timber.d("---Object--" + storageVolumeElement + "i==" + i);
                String path = (String) getPath.invoke(storageVolumeElement);
                Timber.d("---path_total--" + path);
                boolean removable = (Boolean) isRemovableMtd.invoke(storageVolumeElement);
                if (isRemovable == removable) {
                    Timber.d("---path--" + path);
                    return path;
                }
            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return Environment.getExternalStorageDirectory().getAbsolutePath();
    }
```

and check the logcat to discovery the properties of each mount points, and find out the rules.

**Comment by MJsaycon** [comment]
It's returning the same dir as before "/mnt/media_rw/6436-3031".

**Comment by hedzr** [comment]
where the outputs in logcat? post it pls.

**Comment by MJsaycon** [comment]
2019-02-19 18:16:22.269 11475-11475/tech.synq.SynQ D/test_directory: ---length--2
2019-02-19 18:16:22.269 11475-11475/tech.synq.SynQ D/test_directory: ---Object--StorageVolume: Internal storagei==0
2019-02-19 18:16:22.269 11475-11475/tech.synq.SynQ D/test_directory: ---path_total--/storage/emulated/0
2019-02-19 18:16:22.269 11475-11475/tech.synq.SynQ D/test_directory: ---Object--StorageVolume: SanDisk memory card (6436-3031)i==1
2019-02-19 18:16:22.269 11475-11475/tech.synq.SynQ D/test_directory: ---path_total--/mnt/media_rw/6436-3031
2019-02-19 18:16:22.269 11475-11475/tech.synq.SynQ D/test_directory: ---path--/mnt/media_rw/6436-3031

**Comment by hedzr** [comment]
`/mnt/media_rw/6436-3031` is a internal storage, and what about `/storage/emulated/0`?

**Comment by MJsaycon** [comment]
I have an SDCARD in this device which is the SanDisk memory card and it's treating it as a removable sdcard?

**Comment by MJsaycon** [comment]
Both /mnt/media_rw/6436-3031 and /storage/emulated/0 is returning just only the internal? What's wrong with this OS? haha

**Comment by hedzr** [comment]
i have no idea now. i think that's an unsolvable case. while you get any new idea, feel free to @ me.

**Comment by MJsaycon** [comment]
Thank you for the time and helping me. This is so confusing haha.

**Comment by MJsaycon** [comment]
@hedzr Sorry for the waste of time, I solve it by remounting the sdcard.....

**Comment by hedzr** [comment]
:) that's cool!
