### ISSUE TITLE
withOnBackPressedListener not fired

### ISSUE THREAD

**Issue by pockemul** [hedzr/android-file-chooser#42]
Hi,
I define the withOnBackPressedListener option :
```
.withOnBackPressedListener(new ChooserDialog.OnBackPressedListener() {
                            @Override
                            public void onBackPressed(AlertDialog dialog) {
                                Log.i("Qt", "onBackPressed");
                            }
                        })
```

It is never fired.
I have this warning in the log

`W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.`

**Comment by hedzr** [comment]
ChooserDialog is an AlertDialog, so you should link to `withChosenListener` instead of hooking `onBackPressed` directly, see also my sample codes in readme. If you wanna do something at back key pressed, `withNegativeButtonListener` is a better place.

`withOnBackPressedListener` should be deprecated but i'm lazy to document it.
> checked: since 1.1.7, try `withNegativeButton()` and `withNegativeButtonListener()`.
> > And, i will update readme later:
> > try `withNegativeButton()` and `withNegativeButtonListener()` instead of `withOnBackPressedListener`.

**Comment by pockemul** [comment]
In fact i have defined both _withChosenListener_ and _withNegativeButtonListener_, but _withNegativeButtonListener_ is not fired on back. It is is only fired on Cancel

```
                        .withChosenListener(new ChooserDialog.Result() {
                            @Override
                            public void onChoosePath(String path, File pathFile) {
                                Log.i("Qt", "onChoosePath");
                                result = path;
                                dialogSemaphore.release();
                            }
                        })
                        .withOnBackPressedListener(new ChooserDialog.OnBackPressedListener() {
                            @Override
                            public void onBackPressed(AlertDialog dialog) {
                                Log.i("Qt", "onBackPressed");
                                dialogSemaphore.release();
                            }
                        })
                     .withNegativeButtonListener(new DialogInterface.OnClickListener(){
                         @Override
                         public void onClick(DialogInterface dialog, int which) {
                             Log.i("Qt", "Negative");
                             dialogSemaphore.release();
                         }
                     })
                        .build()
                        .show();
```

**Comment by hedzr** [comment]
i got the point: `BACK` not hooked in my keylistener. testing.

**Comment by hedzr** [comment]
just a patch: now the key pressed event works. you can import from jitpack now.

you could sync gradle twice till aar built:
```gradle
	dependencies {
	        implementation 'com.github.hedzr:android-file-chooser:50c5405059'
	}
```

it's not an elegant way but it works. so the annotation `deprecated` be kept.

**Comment by pockemul** [comment]
It works.
Thx a lot. 
you were very reactive.

Regards

**Comment by hedzr** [comment]
i had have a better way to handle the back key:
1. Do not use `onBackListener()`, it's really deprecated;
2. import _new new_ patch and handle `onCancelListener`
   ```java
   .withOnCancelListener(new DialogInterface.OnCancelListener() {
       public void onCancel(DialogInterface dialog) {
           Log.d("CANCEL", "CANCEL");
           dialog.cancel(); // MUST have
       }
   })
   ```

It's better than last patch, because `onCancel` can handle back key or clicked outside the dialog.

##### The _new new_ patch:

```gradle
	dependencies {
	        implementation 'com.github.hedzr:android-file-chooser:9bcf7890aa'
	}
```

have fun.

**Comment by pockemul** [comment]
YES.
That is perfect.
Thank you so mutch.
I just fork the repository. Even if my skills in java and Android are very low, i will try to add fileSaveChooser function.
Navigate to a directory and ask for a fileName. Exactly the same than New Directory but without creating the file.

**Comment by hedzr** [comment]
expecting pr, u r welcome.

**Comment by Guiorgy** [comment]
The idea of having a back key listener is that one might want different outcomes between pressing cancel and going back. I shamelessly took this idea from [orhanobuts'](https://github.com/orhanobut) [DialogPlus](https://github.com/orhanobut/dialogplus). Honestly, I haven't used it (yet), but... Guess deprecating it is ok too.
