### ISSUE TITLE
.with(this) in the sample code is obsolete

### ISSUE THREAD

**Issue by zipswich** [hedzr/android-file-chooser#44]
It should be replaced with 
`ChooserDialog(activity)...`

**Comment by hedzr** [comment]
Right. It was there just because the old `.with(this)` is still works for compatibility.

**Comment by hedzr** [comment]
i'll update the codes.

**Comment by zipswich** [comment]
Thank you for the great tool.
I am wondering if if it is worth mentioning the demo code needs to be run on the UI thread though this can be found out quickly in use.

**Comment by hedzr** [comment]
Well, any ui widgets, dialogs, controls should be placed to main UI thread, isn't its?
If doubt exists, try RxAndroid.
As your wish, a NOTE will be put up later.

**Comment by hedzr** [comment]
should be closed

**Comment by zipswich** [comment]
Thank you.
