### ISSUE TITLE
Does not display the name of a selected folder

### ISSUE THREAD

**Issue by zipswich** [hedzr/android-file-chooser#45]
Suppose the following is the start screen:
![image](https://user-images.githubusercontent.com/6095671/53289178-b84db800-3760-11e9-96b1-2905ee2ce7df.png)
If one taps folder "Download", the following is shown with the folder name "Download" nowhere to be found:
![image](https://user-images.githubusercontent.com/6095671/53289250-c0f2be00-3761-11e9-9ee4-579726099c3b.png)
It actually shows the contents of folder "Download".
I am wondering if I am missing a parameter to enable the display of the selected folder name.
At this point time, this is the only missing part that I have found to prevent it from being as good as a file choose can be for my use.

**Comment by hedzr** [comment]
just released at 1.1.15. so jcenter is ready now.

**Comment by hedzr** [comment]
`.titleFollowsDir(true)` is what you want.

**Comment by zipswich** [comment]
Thanks a lot.   It is perfect now!  It is puzzling that Google has not provided such a frequently used function for 10-year old Android.

**Comment by zipswich** [comment]
Thanks a lot. It is perfect now! 
![image](https://user-images.githubusercontent.com/6095671/53311928-f641fd80-3880-11e9-8262-36aac5f8df1c.png)


It is puzzling that Google has not provided such a frequently used function for 10-year old Android.

**Comment by hedzr** [comment]
my honor.

**Comment by Guiorgy** [comment]
nice idea!
