### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by josydeleon** [hedzr/android-file-chooser#5]
I am getting this issue when I use it

`E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File[] java.io.File.listFiles(java.io.FileFilter)' on a null object reference`

**Comment by hedzr** [comment]
more details please?

**Comment by bostrot** [comment]
@jossydeleon Have you assigned the "startFile"? like this: `.withStartFile(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).getAbsolutePath())`

**Comment by hedzr** [comment]
@jossydeleon maybe click button twice, if that, improve demo app button click listener or yourselves

**Comment by SeppPenner** [comment]
This occurs whenever you try to start the ChooserDialog with Directories only and don't assign a start directory as @bostrot told. Hade the same issue and the hint from @bostrot fixed it.

**Comment by hedzr** [comment]
got it. thank you,
.
