### ISSUE TITLE
I get an Invoke-customs error when buidling with 1.1.16

### ISSUE THREAD

**Issue by ytheekshana** [hedzr/android-file-chooser#53]
I get an issue like this when building with 1.1.16

Error: Invoke-customs are only supported starting with Android O (--min-api 26)

Latest Android Studio Stable

**Comment by hedzr** [comment]
Java 8 enabled from 1.1.16. You could add compartibility in app/build.gradle: 

```gradle
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

See also:
- https://stackoverflow.com/questions/49891730/invoke-customs-are-only-supported-starting-with-android-0-min-api-26

**Comment by Guiorgy** [comment]
I think it should say somewhere that target sdk is 1.8, and that it was changed in 1.1.16 update, no?

**Comment by ytheekshana** [comment]
> 
> 
> Java 8 enabled from 1.1.16. You could add compartibility in app/build.gradle:
> 
> ```groovy-gradle
> android {
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> }
> ```
> 
> See also:
> 
>     * https://stackoverflow.com/questions/49891730/invoke-customs-are-only-supported-starting-with-android-0-min-api-26

Perfect. It works

**Comment by Guiorgy** [comment]
this should be close right, hedzr?

**Comment by carlos-mg89** [comment]
Adding the `sourceCompatibility` doesn't fix the Invoke-customs error in my case. Could it be because my minSdkVersion is 19?

**Comment by hedzr** [comment]
have tried a fully clean and rebuild?

**Comment by carlos-mg89** [comment]
@hedzr my bad, that made it work and removed the Invoke-customs issue. Thanks!
