### ISSUE TITLE
Creating a new folder window color bug in dark theme

### ISSUE THREAD

**Issue by ytheekshana** [hedzr/android-file-chooser#55]
As you said [here](https://github.com/hedzr/android-file-chooser/issues/34#issuecomment-444777914), I am using a custom row layout to give a dark mode. But how to change the alert textbox and its text color when creating a new folder. Check the screenshot to get an idea about what I am saying. I checked the demo app in the 1.2.X branch. The same thing happens in it too when in night mode.

see the image
![file-chooser](https://user-images.githubusercontent.com/24976965/53879637-fd150100-4034-11e9-823c-b35dd8764b30.jpg)

**Comment by Guiorgy** [comment]
you cant right now as it is created programatically. the best solution for everyone is probably to create a custom Theme for the library.

**Comment by Guiorgy** [comment]
@ytheekshana, by the way, what theme are you using for the dialog?

**Comment by Guiorgy** [comment]
@ytheekshana, some stylables where added to the library. Could you test them and see if that helps you?

**Comment by ytheekshana** [comment]
> 
> 
> @ytheekshana, some stylables where added to the library. Could you test them and see if that helps you?

Yap. Now it looks perfect.  Can you release the 1.1.17 to public now.

**Comment by Guiorgy** [comment]
@ytheekshana, we are still editing a few things here and there. We are hoping to release it on this weekend though.

**Comment by ytheekshana** [comment]
![1](https://user-images.githubusercontent.com/24976965/54762400-119eef00-4c1a-11e9-9ea9-b0a35a0af9e1.jpg)
![2](https://user-images.githubusercontent.com/24976965/54762401-119eef00-4c1a-11e9-8335-9f6ab39cf6df.jpg)

Why is the window width in the dark mode is small? How can I get the same width as the light version?

**Comment by Guiorgy** [comment]
@ytheekshana, what android is that? I am getting the same width on an api 28 emulator.
If you want to change something like width, it should be in the AlertDialogs theme.
edit. try:
```java
<item name="windowFixedWidthMajor">70%</item>
<item name="windowFixedWidthMinor">70%</item>
```

**Comment by ytheekshana** [comment]
Perfect..... 
Here's a suggestion, 
Please make it possible to change the accent color programmatically. Also, make it possible to toggle the dark theme programmatically.

**Comment by Guiorgy** [comment]
@ytheekshana, change accent color programmatically? why? can't you do it through the styles? do you mean changing colors and theme while the dialog is showing?

also, the 'dark theme' is not part of the library, but just an example in the demo app. At least not as of right now anyways.
