### ISSUE TITLE
The cancel and ok buttons display on the bottom-left corner of the dialog

### ISSUE THREAD

**Issue by lxfly2000** [hedzr/android-file-chooser#62]
I'm using 1.1.17 version and codes from README.md choosing a folder, the choose and cancel buttons are not displayed on the bottom-right corner as I expect while 1.1.16 version works fine.

**Comment by Guiorgy** [comment]
That was a side effect of an attemt to remove an inconsistency of the buttons order/gravity dependent on the theme. For the next release I have set the order to:
neutral (options) left, negative (cancel) center, positive (ok) right.
![Screenshot_1555310787](https://user-images.githubusercontent.com/27736965/56112343-dae39c80-5f6b-11e9-9a1a-e21012f4368f.png)
Will this be alright, or would you suggest differently?

**Comment by lxfly2000** [comment]
That's ok. In my app the menu button “⋮” is not needed so just like the normal AlertDialog, place the cancel and choose buttons on the right if I don't call `enableOptions(true)`.

**Comment by Guiorgy** [comment]
![Screenshot_1555327780](https://user-images.githubusercontent.com/27736965/56129579-8d7b2580-5f93-11e9-81ff-f01a04566230.png)
is this what you wanted?

**Comment by lxfly2000** [comment]
Yes

**Comment by Guiorgy** [comment]
got it. will be changed in the next release.
you can test the changes with this until release:
`implementation 'com.github.hedzr:android-file-chooser:experimental~dpad-SNAPSHOT'`
if you find any more problems, or have any suggestions, please don't hesitate

**Comment by Guiorgy** [comment]
1.1.19 out, please confirm that the problem has been solved.
