### ISSUE TITLE
如何设置这里的字体和颜色？

### ISSUE THREAD

**Issue by hegelsu** [hedzr/android-file-chooser#64]
![1](https://user-images.githubusercontent.com/6879123/57195070-c6019400-6f80-11e9-8e21-3745e8c9e561.png)

**Comment by Guiorgy** [comment]
you can either try to modify it through a custom theme:
```xml
    <style name="FileChooserPathViewStyle">
        <item name="android:textColor">#40ff0000</item>
        <item name="android:textSize">16sp</item>
        <item name="fileChooserPathViewDisplayRoot">false</item>
    </style>
```
please, check the styles.xml file for an example in the demo app.

another one would be using the `public ChooserDialog customizePathView(CustomizePathView callback)` method:
```java
dialog.customizePathView(textView -> {
    textView.setCompoundDrawablesWithIntrinsicBounds(icon, null, null, null);
})...
```

**Comment by hedzr** [comment]
well done. and @Guiorgy have u ever study chinese?

**Comment by Guiorgy** [comment]
nope, google sensei comes for the rescue :)

**Comment by hegelsu** [comment]
thx.

**Comment by hegelsu** [comment]
上图中的“Choose a file"的字体大小和颜色可以设置么？

**Comment by Guiorgy** [comment]
yes, a **_lot_** of things can be customized through custom themes:
```xml
<style name="FileChooserTitleStyle_Dark" parent="FileChooserTitleStyle">
    <item name="android:textAppearance">@style/TextAppearance.AppCompat.Title.Inverse</item>
    <item name="android:textColor">@android:color/holo_blue_light</item>
    <item name="android:textSize">8sp</item>
</style>
```
![Screenshot_1557319870](https://user-images.githubusercontent.com/27736965/57376635-92598080-71b1-11e9-8417-3f48132bbe83.png)

refere to the demo app for an example of a 'Dark' theme

**Comment by hegelsu** [comment]
OK
