### ISSUE TITLE
Remove kotlin plugin from library

### ISSUE THREAD

**Issue by joielechong** [hedzr/android-file-chooser#71]
For the library module, I think you can safely remove the `apply plugin: 'kotlin-android'` and `implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version" ` from dependencies. I try running the sample app with the two above removed and the app is running smoothly. 

I can send you a PR to let me remove them.

**Comment by hedzr** [comment]
You're right, @joielechong , that's my bad.
Waiting for the PR on `master`, we would release it with our works.

**Comment by joielechong** [comment]
@hedzr: I have create a PR.. please take a look. ;)

**Comment by joielechong** [comment]
Thanks for the merge!
