### ISSUE TITLE
File size is 0 if file is smaller than 1024 bytes

### ISSUE THREAD

**Issue by nugatritter** [hedzr/android-file-chooser#75]

**Comment by nugatritter** [comment]
When you list files with size smaller than 1024 bytes (1kB) they will be displayed with file size "0 KB". The user could think that these files are empty.

**Comment by Guiorgy** [comment]
use

```
dependencies {
	implementation 'com.github.hedzr:android-file-chooser:1.2.0-SNAPSHOT'
}
```

**Comment by nugatritter** [comment]
#75 fixed the issue
Thank you for extremely fast solution!
